# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

menu: #配置页头显示哪些菜单
#  Home: /
  Archives: /archives
  Reading: /reading
  About: /about
#  Guestbook: /about

# Site
title: Liecol's Blog
subtitle: 技术，源于对生活的分享，所谓迷茫，就是才华配不上梦想！
keyword: liecol-晓斌, 高晓斌博客, 高晓斌网站 高晓斌blog, php, 高晓斌
description: liecol-晓斌的个人网站，技术，源于对生活的分享，所谓迷茫，就是才华配不上梦想。我是liecol，欢迎进入我的个人网站。
author: Liecol Gao
language: zh-CN
timezone:

weibo_username: liecol
# zhihu_username: Demonbane
github_username: liecol-gao
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://bin.bloggao.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Site settings
SEOTitle: Liecol-晓斌的博客 | Liecol's Blog
header-img: img/home-bg.jpg

# Directory
source_dir: source
public_dir: public
tag_dir: /tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
featured-condition-size: 1
default_category: uncategorized
category_map:
tag_map:
tags: [
    {
        name: "php"
    },{
        name: "JavaScript"
    },{
        name: "linux"
    },{
        name: "python"
    },{
        name: "mysql"
    },{
        name: "nodejs"
    }
]

categories: [
    {
        name: "php"
    },{
        name: "JavaScript"
    },{
        name: "linux"
    },{
        name: "python"
    },{
        name: "mysql"
    },{
        name: "nodejs"
    }
]

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: huxblog
theme: landscape
# theme: landscape2
# theme: liecol_1
## theme: noderce
# theme: master

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "世界那么大，我只想安安静静写代码！"
sidebar-avatar: img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


duoshuo_username: liecol
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true  

featured-tags: true

friends: [
    # {
    #     title: "liecol's shop",
    #     href: "http://shop.bloggao.cn"
    # },{
    #     title: "liecol's zpw",
    #     href: "http://zpw.bloggao.cn"
    # },{
    #     title: "liecol's KD",
    #     href: "http://ltkd.bloggao.cn"
    # },{
    #     title: "liecol's Home",
    #     href: "http://www.bloggao.cn"
    # },
    {
        title: "菜鸟-Miao",
        href: "http://blog.newbmiao.com"
    }
    
]

# 自动生成sitemap
baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml

baidu_url_submit:
  count: 4 ## 比如3，代表提交最新的三个链接
  host: bin.bloggao.cn ## 在百度站长平台中注册的域名
  token: it6CwQCgbNdyi2Uu ## 请注意这是您的秘钥， 请不要发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# npm install hexo-deployer-git --save
#deploy:
#  type: git
#  repo: https://github.com/liecol-gao/liecol-gao.github.io.git,master
#  repo: https://gitcafe.com/liecol/liecol.git,gitcafe-pages
 # branch: master

deploy:
- type: git
  repo: 
    github: https://github.com/liecol-gao/liecol-gao.github.io.git,master
    coding: https://git.coding.net/liecol/liecol.git,coding-pages
- type: baidu_url_submitter
